import os from "os";
import path from "path";
import type { Subject, Schedule, TimetablePreset } from "../context/app-context";
import { DAYS } from "../context/app-context";

let canvasModule: typeof import("canvas") | null = null;

async function loadCanvas() {
  if (!canvasModule) {
    try {
      canvasModule = await import("canvas");
    } catch {
      throw new Error("canvas package not installed. Run 'bun add canvas' first.");
    }
  }
  return canvasModule;
}

interface TimetableData {
  subjects: Subject[];
  schedule: Schedule;
  preset: TimetablePreset;
}

export async function generateTimetableImage(data: TimetableData): Promise<string> {
  const canvas = await loadCanvas();
  const { createCanvas } = canvas;
  
  const { subjects, schedule, preset } = data;
  
  const canvasWidth = 1400;
  const headerHeight = 80;
  const footerHeight = 40;
  const dayHeaderHeight = 40;
  const slotHeight = 100;
  const colWidth = (canvasWidth - 120) / 5;
  const timeColWidth = 120;
  
  const canvasHeight = headerHeight + dayHeaderHeight + (slotHeight * 8) + footerHeight;
  
  const cvs = createCanvas(canvasWidth, canvasHeight);
  const ctx = cvs.getContext("2d");
  
  // Background
  ctx.fillStyle = "#ffffff";
  ctx.fillRect(0, 0, canvasWidth, canvasHeight);
  
  // Header
  ctx.fillStyle = "#1a1a2e";
  ctx.fillRect(0, 0, canvasWidth, headerHeight);
  
  ctx.fillStyle = "#ffffff";
  ctx.font = "bold 28px Arial";
  ctx.textAlign = "center";
  ctx.fillText("Weekly Timetable", canvasWidth / 2, 40);
  
  ctx.font = "14px Arial";
  ctx.fillStyle = "#aaaaaa";
  const dateStr = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  ctx.fillText(dateStr, canvasWidth / 2, 65);
  
  // Footer
  ctx.fillStyle = "#f0f0f0";
  ctx.fillRect(0, canvasHeight - footerHeight, canvasWidth, footerHeight);
  ctx.fillStyle = "#666666";
  ctx.font = "12px Arial";
  ctx.textAlign = "center";
  ctx.fillText("Generated by Attendance Tracker TUI", canvasWidth / 2, canvasHeight - 15);
  
  // Draw grid
  const startY = headerHeight + dayHeaderHeight;
  
  // Time column header
  ctx.fillStyle = "#e0e0e0";
  ctx.fillRect(0, headerHeight, timeColWidth, dayHeaderHeight);
  ctx.fillStyle = "#333333";
  ctx.font = "bold 12px Arial";
  ctx.textAlign = "center";
  ctx.fillText("Time", timeColWidth / 2, headerHeight + 25);
  
  // Day headers
  ctx.fillStyle = "#e0e0e0";
  DAYS.forEach((day, idx) => {
    const x = timeColWidth + idx * colWidth;
    ctx.fillStyle = "#e0e0e0";
    ctx.fillRect(x, headerHeight, colWidth, dayHeaderHeight);
    ctx.fillStyle = "#333333";
    ctx.font = "bold 12px Arial";
    ctx.fillText(day, x + colWidth / 2, headerHeight + 25);
  });
  
  // Grid lines and cell content
  for (let slotIdx = 0; slotIdx < 8; slotIdx++) {
    const y = startY + slotIdx * slotHeight;
    const timeLabel = preset.slots[slotIdx] || "";
    
    // Time column
    ctx.fillStyle = "#f8f8f8";
    ctx.fillRect(0, y, timeColWidth, slotHeight);
    ctx.fillStyle = "#333333";
    ctx.font = "bold 11px Arial";
    ctx.textAlign = "center";
    ctx.fillText(`Slot ${slotIdx + 1}`, timeColWidth / 2, y + 20);
    if (timeLabel) {
      ctx.font = "10px Arial";
      ctx.fillStyle = "#666666";
      ctx.fillText(timeLabel, timeColWidth / 2, y + 40);
    }
    
    // Day columns
    DAYS.forEach((day, dayIdx) => {
      const x = timeColWidth + dayIdx * colWidth;
      const subjectId = schedule[day]?.[slotIdx];
      
      // Cell border
      ctx.strokeStyle = "#dddddd";
      ctx.lineWidth = 1;
      ctx.strokeRect(x, y, colWidth, slotHeight);
      
      if (subjectId && subjectId !== "FREE") {
        const subject = subjects.find((s) => s.id === subjectId);
        if (subject) {
          // Background color for subject
          ctx.fillStyle = getColorHex(subject.color);
          ctx.fillRect(x + 2, y + 2, colWidth - 4, slotHeight - 4);
          
          // Subject code (bold)
          ctx.fillStyle = "#000000";
          ctx.font = "bold 14px Arial";
          ctx.textAlign = "left";
          ctx.fillText(`[${subject.code}]`, x + 8, y + 25);
          
          // Subject name
          ctx.font = "10px Arial";
          ctx.fillStyle = "#333333";
          const maxNameLen = Math.floor((colWidth - 16) / 6);
          const shortName = subject.name.length > maxNameLen 
            ? subject.name.substring(0, maxNameLen) + "..." 
            : subject.name;
          ctx.fillText(shortName, x + 8, y + 42);
          
          // Room
          if (subject.room) {
            ctx.font = "9px Arial";
            ctx.fillStyle = "#444444";
            ctx.fillText(`Room: ${subject.room}`, x + 8, y + 58);
          }
          
          // Instructor
          if (subject.instructor) {
            ctx.font = "9px Arial";
            ctx.fillStyle = "#444444";
            const maxInstrLen = Math.floor((colWidth - 16) / 6);
            const shortInstr = subject.instructor.length > maxInstrLen
              ? subject.instructor.substring(0, maxInstrLen) + "..."
              : subject.instructor;
            ctx.fillText(shortInstr, x + 8, y + 72);
          }
          
          // Credits
          if (subject.credits) {
            ctx.font = "8px Arial";
            ctx.fillStyle = "#666666";
            ctx.fillText(`${subject.credits} credits`, x + 8, y + 88);
          }
        }
      }
    });
  }
  
  // Save to file
  const fileName = `timetable-${new Date().toISOString().split("T")[0]}.png`;
  const filePath = path.join(os.homedir(), fileName);
  
  const buffer = cvs.toBuffer("image/png");
  await Bun.write(filePath, buffer);
  
  return filePath;
}

function getColorHex(colorName: string): string {
  const colorMap: Record<string, string> = {
    cyan: "#00bcd4",
    red: "#f44336",
    green: "#4caf50",
    yellow: "#ffeb3b",
    magenta: "#e91e63",
    white: "#f5f5f5",
    gray: "#9e9e9e",
  };
  
  return colorMap[colorName.toLowerCase()] || "#00bcd4";
}
